# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
    - refs/tags/v*
    - dev
pr:
- master


pool:
  name: Hosted VS2017

steps:
- task: NodeTool@0
  displayName: 'Use Node 12.16.1'
  inputs:
    versionSpec: 12.16.1
    architecture: x86

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: './'
  displayName: 'install npm submodules'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      npm run node_x86
      rm lib/*.ilk
      rm lib/*d.dll
      mv lib/cvip.pdb cvip.pdb
      ls lib
  displayName: 'build node_x86'

- task: cURLUploader@2
  displayName: 'Upload pdb'
  inputs:
    files: 'cvip.pdb'
    serviceEndpoint: 'csding.net'
    remotePath: 'repertory/cxb/cvip.pdb?version=$(Build.SourceBranchName)-node-x86'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))

- task: ArchiveFiles@2
  displayName: 'Archive lib'
  inputs:
    rootFolderOrFile: lib
    includeRootFolder: false
    archiveType: tar
    archiveFile: 'cvip.tar.gz'

- task: cURLUploader@2
  displayName: 'Upload cvip.node'
  inputs:
    files: 'cvip.tar.gz'
    serviceEndpoint: 'csding.net'
    remotePath: 'repertory/cxb/cvip.tar.gz?version=$(Build.SourceBranchName)-windows-x86'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
  
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: './'
    customCommand: 'run build'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
  
- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: './'
    customRegistry: 'useFeed'
    publishEndpoint: 'npmjs.org'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))