# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  name: Hosted VS2017
steps:
- script: |
   pwd
   ls -la
   
  displayName: 'download opencv && build typescript'
- task: GitHubRelease@0
  inputs:
    gitHubConnection: 'ga-connect'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'auto'
    releaseNotesFile: 'ChangeLog'
    addChangeLog: false